pipeline {
    agent {
        node {
          label 'master'
        }
      
    }
   
      
     stages {
     stage('Checkout SCM') {
            steps{
                sh '''
                cd /home/ubuntu/workspace/EdgeCSP/test_job
                #rm -rf *
                pwd
                ls
                printenv | sort
                pwd
                echo $WORKSPACE
                '''
            }
  
    
     }
}
  }
